project_name: customer-service

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/rest

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - "ghcr.io/s6-bikepack/customer-service:{{ .Version }}"
      - "ghcr.io/s6-bikepack/customer-service:latest"
      - "bikepack.azurecr.io/bikepack/customer-service:latest"
    dockerfile: Dockerfile.release
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/s6-bikepack/customer-service
      - --label=org.opencontainers.image.source=https://github.com/s6-bikepack/customer-service
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc