FROM golang:1.18-alpine

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

COPY ./ ./
RUN go mod download
RUN go get github.com/rakyll/gotest
RUN go install github.com/rakyll/gotest
RUN go mod verify