// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type RiderInput struct {
	Name   string `json:"name"`
	Status int    `json:"status"`
}
