// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Rider struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Status   string    `json:"status"`
	Location *Location `json:"location"`
}

type RiderInput struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}
