definitions:
  dto.BodyCreateCustomer:
    properties:
      id:
        type: string
      serviceArea:
        type: integer
    type: object
  dto.BodyUpdateServiceArea:
    properties:
      serviceArea:
        type: integer
    type: object
  dto.CustomerResponse:
    properties:
      id:
        type: string
      last_name:
        type: string
      name:
        type: string
      service_area:
        type: integer
    type: object
  dto.customerResponse:
    properties:
      id:
        type: string
      name:
        type: string
      service_area:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/customers:
    get:
      consumes:
      - application/json
      description: gets all customers in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.customerResponse'
            type: array
      summary: get all customers
    post:
      consumes:
      - application/json
      description: creates a new customer
      parameters:
      - description: Add customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/dto.BodyCreateCustomer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CustomerResponse'
      summary: create customer
  /api/customers/{id}:
    get:
      description: gets a customer from the system by its ID
      parameters:
      - description: Customer id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CustomerResponse'
      summary: get customer
  /api/customers/{id}/service-area:
    put:
      consumes:
      - application/json
      description: updates a customers service area
      parameters:
      - description: Update customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/dto.BodyUpdateServiceArea'
      - description: Customer id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CustomerResponse'
      summary: update customers service area
swagger: "2.0"
