definitions:
  domain.Customer:
    properties:
      email:
        type: string
      id:
        type: string
      lastName:
        type: string
      name:
        type: string
      serviceArea:
        type: integer
    type: object
  dto.BodyCreateCustomer:
    properties:
      email:
        type: string
      lastName:
        type: string
      name:
        type: string
    type: object
  dto.BodyUpdateCustomer:
    properties:
      email:
        type: string
      lastName:
        type: string
      name:
        type: string
    type: object
  dto.BodyUpdateServiceArea:
    properties:
      serviceArea:
        type: integer
    type: object
  dto.ResponseCreateCustomer:
    properties:
      email:
        type: string
      id:
        type: string
      lastName:
        type: string
      name:
        type: string
      serviceArea:
        type: integer
    type: object
  dto.ResponseUpdateCustomer:
    properties:
      email:
        type: string
      id:
        type: string
      lastName:
        type: string
      name:
        type: string
      serviceArea:
        type: integer
    type: object
  dto.ResponseUpdateServiceArea:
    properties:
      email:
        type: string
      id:
        type: string
      lastName:
        type: string
      name:
        type: string
      serviceArea:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/customers:
    get:
      consumes:
      - application/json
      description: gets all customers in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Customer'
            type: array
      summary: get all customers
    post:
      consumes:
      - application/json
      description: creates a new customer
      parameters:
      - description: Add customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/dto.BodyCreateCustomer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseCreateCustomer'
      summary: create customer
  /api/customers/{id}:
    get:
      description: gets a customer from the system by its ID
      parameters:
      - description: Customer id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Customer'
      summary: get customer
    put:
      consumes:
      - application/json
      description: updates a customers name, last name and/or email
      parameters:
      - description: Update customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/dto.BodyUpdateCustomer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseUpdateCustomer'
      summary: update customer details
  /api/customers/service-area{id}:
    put:
      consumes:
      - application/json
      description: updates a customers service area
      parameters:
      - description: Update customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/dto.BodyUpdateServiceArea'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseUpdateServiceArea'
      summary: update customers service area
swagger: "2.0"
